### ISSUE TITLE
Angular integration

### ISSUE THREAD

**Issue by dalybouba** [yermolim/ts-gantt#17]
please how can I integrated with angular

**Comment by SuzGori** [comment]
@dalybouba 

hi!
Just import and use as normal.
It might be a good idea to use a service class or something to update tasks.

install
```
npm install ts-gantt
```


write component.ts
ex)

```typescript
chart: TsGantt

ngOnChanges() {
  this.chart = new TsGantt('#gantt-container');
}

```

I think ngOnChanges can be changed to ngOnInit.
In my case, I changed it to ngOnChanges because I wanted it to change when the value is updated.
By the way, task uses the following Interface.
* TsGanttTaskModel


write html
```html

<div id="gantt-container"></div>
```
